NPC0100Project/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NPC0100Project.Areas.Identity.Data;
using NPC0100Project.Authorization;
using NPC0100Project.Data;
using NPC0100Project.Models;
using NPC0100Project.Repository;


namespace NPC0100Project.Controllers
{
    public class ProjectController : Controller
    {
        //private readonly ProjectContext _context;
        private readonly IRepository<Project, int> _projectRepository;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IAuthorizationService _authorizationService;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public ProjectController(IRepository<Project,int> projectRepository, UserManager<ApplicationUser> userManager, 
            IAuthorizationService authorizationService, IWebHostEnvironment hostingEnvironment)
        {
            _projectRepository = projectRepository;
            _userManager = userManager;
            _authorizationService = authorizationService;
            _hostingEnvironment = hostingEnvironment;
        }

        protected AuthDbContext Context { get; }
        //protected IAuthorizationService AuthorizationService { get; }
        //protected UserManager<ApplicationUser> UserManager { get; }

        // GET: Project
        //public async Task<IActionResult> Index()
        //{
        //    //return View(await _context.Projects.ToListAsync());
        //    //IProjectRepository objProjectRepository = new ProjectRepository(_context);
        //    var projects = await _projectRepository.GetAll();
        //    return View(projects);
        //}



        //[HttpPost]
        [Authorize]
        public IActionResult Index(string sortOrder)
        {
            ViewBag.MemberSort = sortOrder == "Members" ? "Member_desc" : "Members";
            var query = _projectRepository.GetAllQueryable();
            switch (sortOrder)
            {
                case "Members":
                    query = query.OrderBy(p => p.Members);
                    break;
                case "Member_desc":
                    query = query.OrderByDescending(p => p.Members);
                    break;
                default:
                    break;
            }
            return View(query.ToList());
        }

        //GET: Project/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Project/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Project project)
        {
            if (ModelState.IsValid)
            {

                //var user = await _userManager.FindByIdAsync(userId);
                //if (user == null)
                //{
                //    ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                //    return View("NotFound");
                //}
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId
                project.OwnerID = userId;
                //project.OwnerID = userId;
                // requires using ContactManager.Authorization;
                var isAuthorized = await _authorizationService.AuthorizeAsync(
                                                            User, project,
                                                            ContactOperations.Create);
                if (!isAuthorized.Succeeded)
                {
                    return Forbid();
                }


                await _projectRepository.Insert(project);
                await _projectRepository.Save();                
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }




        // GET: Project/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var project = _projectRepository.GetById(id);
            var project = await _projectRepository.GetById((int)id);

            if (project == null)
            {
                return NotFound();
            }

            var isAuthorized = await _authorizationService.AuthorizeAsync(
                                                     User, project,
                                                     ContactOperations.Delete);
            if (!isAuthorized.Succeeded)
            {
                return Forbid();
            }


            return View(project);
        }

        // POST: Project/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var project = await _projectRepository.GetById((int)id);

            var isAuthorized = await _authorizationService.AuthorizeAsync(
                                                     User, project,
                                                     ContactOperations.Delete);
            if (!isAuthorized.Succeeded)
            {
                return Forbid();
            }

            await _projectRepository.Delete(id);
            await _projectRepository.Save();
            
            return RedirectToAction(nameof(Index));
        }

        // GET: Project/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _projectRepository.GetById((int)id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }



        // GET: Project/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _projectRepository.GetById((int)id);
            if (project == null)
            {
                return NotFound();
            }
            return View(project);
        }

        // POST: Project/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ProjectName,Description,Members")] Project project)
        {
            if (id != project.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _projectRepository.Update(project);
                    await _projectRepository.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }


        public async Task<IActionResult> Excel()
        {
            using (var workbook = new XLWorkbook())
            {

                var projects = await _projectRepository.GetAll();

                var worksheet = workbook.Worksheets.Add("Projects");
                var currentRow = 2;
                var title = worksheet.Range("B1");
                var header = worksheet.Range("A2:C2");
                var Allcontent = worksheet.Range("A2:C"+ (projects.Count()+2).ToString());
                

                title.Value = "我們的專案";
                title.Style.Font.FontName = "標楷體";
                title.Style.Font.FontSize = 30;
                title.Style.Fill.BackgroundColor = XLColor.FromArgb(173, 223, 247);
                title.Style.Font.FontColor = XLColor.FromArgb(58, 92, 228);
                title.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                title.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;

                header.Style.Fill.BackgroundColor = XLColor.FromArgb(186,253,215);
                header.Style.Font.FontColor = XLColor.Black;
                header.Style.Font.Bold = true;
                header.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

                worksheet.Column("B").Style.Alignment.WrapText = false;

                worksheet.Column("A").Width = 15;
                worksheet.Column("B").Width = 80;
                worksheet.Column("C").Width = 30;
                worksheet.Row(1).Height = 42;

                Allcontent.Style.Border.InsideBorder = XLBorderStyleValues.Thin;
                Allcontent.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;


                worksheet.Cell(currentRow, 1).Value = "Project Name";
                worksheet.Cell(currentRow, 2).Value = "Description";
                worksheet.Cell(currentRow, 3).Value = "Members";
                worksheet.RowHeight = 15;


                

                foreach (var pj in projects)
                {
                    currentRow++;
                    worksheet.Cell(currentRow, 1).Value = pj.ProjectName;

NPC0100Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NPC0100Project</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://code.iconify.design/2/2.0.3/iconify.min.js"></script>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="icon" type="image/x-icon" href="~/Images/pIconx.png">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="~/css/site.css" />*@
    @*<link href="~/css/style.css" rel="stylesheet" />*@
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600" />
    <link rel="stylesheet" href="~/css/all.min.css" />
    @*<link rel="stylesheet" href="~/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/tooplate-style.css" />
    <style>
        #logout {
            display: inline;
            position: absolute;
        }


    </style>
</head>
<body>
    <div id="logout">
        <partial name="_LoginPartial.cshtml" />
    </div>

    <div class="container" id="home">
        <div class="col-12 text-center">
            <div class="tm-page-header">
                <span class="iconify-inline fas fa-4x fa-chart-bar mr-4" data-icon="file-icons:microsoft-project"></span>
                <h1 class="d-inline-block text-uppercase">Projects</h1>

            </div>
        </div>
    </div>

    <!-- navbar -->
    <div class="tm-nav-section">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="navbar navbar-expand-md navbar-light">
                        <button class="navbar-toggler"
                                type="button"
                                data-toggle="collapse"
                                data-target="#tmMainNav"
                                aria-controls="tmMainNav"
                                aria-expanded="false"
                                aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse" id="tmMainNav">
                            <ul class="navbar-nav mx-auto tm-navbar-nav">
                                <li class="nav-item active">
                                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Project" asp-action="Index">彙總表</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Project" asp-action="Create">專案提報</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="http://10.3.61.129:9527/" target="_blank">資源共享區</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="https://gitlab.com/lojyehuang/MVC_NPC0100Project" target="_blank">本站GitLab</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link external" href="#FB">Page</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>


    @*<br />
    <img
        src="~/Images/sample2.png"
        style="
        position: absolute;
        width: 40%;
        margin-left: 30%;
        opacity:0.5;
        margin-right: auto;" />*@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - NPC0100Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>